### ISSUE TITLE
Card carousel prev/next bouton rendering on narrow screens w/ iOS

### ISSUE THREAD

**Issue by eschweitzer78** [digitalnsw/nsw-design-system#417] opened 2024-06-11 00:36 UTC
**Describe the bug**
Card carousel: on narrow screen devices with Safari iOS, prev/next button icons are pushed towards the right and no longer appear centred. The issue is also visible on Chrome iOS.

**To Reproduce**
1. Use a narrow screen device (e.g. iPhone 13)
2. Go to the [carousel card demo page](https://digitalnsw.github.io/nsw-design-system/components/card-carousel/blank.html) 
3. See error, the arrows are somewhat to the right of the button as highlighted in the screenshot below

**Expected behavior**
Would expect the arrow icon to remain at the centre.

**Screenshots**
![image](https://github.com/digitalnsw/nsw-design-system/assets/20468027/f9ebb371-92fe-4a47-bb18-8c1ea6f8d889)

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 17.5.1
 - Browser: Safari
 - Version: 17.5

**Additional context**
It appears that setting `padding:0` on `.nsw-carousel button` redresses it. The padding is set by default to 16px on each side on iOS Safari (it derives from button padding-inline-end and padding-inline-start which are set to 16px) whereas it sits at 6px on Safari desktop (and isn't set on Chrome desktop).

**Comment by laurenhitchon** [comment] 2024-06-11 07:11
Hello again @eschweitzer78, 

Thank you for bringing this issue to our attention and for providing such a detailed report. We appreciate your efforts to help improve our components.

We will review and test your proposed fix and work on implementing a solution that ensures the button icons remain centered on narrow screen devices. We will keep you updated on our progress and notify you once the fix is deployed.

**Comment by laurenhitchon** [comment] 2024-06-12 23:16
Hi @eschweitzer78,

A pull request has been completed and merged in the last 24 hours to address the problem you reported with the card carousel's previous/next button icons being misaligned on narrow screen devices using Safari iOS and Chrome iOS, where the icons are pushed to the right instead of being centered.

We reviewed and implemented your suggested fix by setting `padding: 0` on the `.nsw-carousel` button class in the `_carousel.scss` file. This change corrects the alignment issue caused by default padding values in iOS browsers. https://github.com/digitalnsw/nsw-design-system/pull/418/files#diff-10182913edc91376ea3660f94a350ca6a2dca4d4022e9c3ba935ddd89ce69257

We believe this fix should resolve the issue you've raised. Please review the update and let us know if you have any more problems.

**Closed** 2024-06-12 23:18 UTC
