### ISSUE TITLE
Card Carousel with drag on, drag behaviour probably not what's expected

### ISSUE THREAD

**Issue by eschweitzer78** [digitalnsw/nsw-design-system#414] opened 2024-06-08 11:23 UTC
**Describe the bug**
Hello and thank you again for all the great work you do! I have extensively reviewed the Card Carousel component and when data-drag="on" I think the drag behaviour is not exactly what's expected -- or at least the code is not working as it should.

While you drag the carousel, its contents should move accordingly (based on the carousel's js logic). However, I find that nothing moves until the drag ends.

**To Reproduce**
1. Modify the [Card Carousel demo page](https://digitalnsw.github.io/nsw-design-system/components/card-carousel/blank.html) so that one of the carousels has data-drag="on"
2. Place the mouse pointer (or finger on a handheld device) over that carousel and start dragging
3. See error as the carousel does not move until the drag ends even though the javascript for carousel sets a x translation while dragging (see `carousel.js` line 197)

**Expected behavior**
The carousel should move while it's dragged or, if this is not wished and you'd like the carousel to change only when the drag/swipe motion is done, the inoperative js logic should be removed. See additional context below for a suggested fix.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 17.5

**Additional context**
According to my analysis, the translation of the carousel does not happen because the event data received by the inline dragging event handler in `carousel.js` line 190 is wrong (with x a `NaN`).

You should amend `swipe-content.js` to correct the implementation of the `drag` method as follows (the current implementation is such that the `emitDrag` method receives a timestamp from `requestAnimationFrame` vs. the event details -- the bind is unnecessary as arrow functions keep the `this` context and event is lost along the way as there is no closure):

```
  drag(event) {
    if (!this.dragging) return;

    if (!window.requestAnimationFrame) {
      this.intervalId = setTimeout(() => { this.emitDrag(event) }, 250);
    } else {
      this.intervalId = window.requestAnimationFrame(() => { this.emitDrag(event) });
    }
  }

```

**Comment by laurenhitchon** [comment] 2024-06-11 07:07
Hi @eschweitzer78,

Thank you for your detailed report on the Card Carousel component's drag behaviour. We appreciate your thorough analysis and the suggested fix.

We will review and test your proposed fix and work on implementing a solution that ensures the drag behavior works as intended. We will keep you updated on our progress and notify you once the fix is deployed.

**Comment by laurenhitchon** [comment] 2024-06-12 23:09
Hi @eschweitzer78,

A pull request has been completed and merged in the last 24 hours to address the issue with the card carousel component's drag behaviour.

Specifically, we used your suggested changes to `swipe-content.js` to ensure the carousel updates its position dynamically during drag actions. Also, we made the following updates:

- JavaScript Enhancements: Updated `carousel.js` to complement the changes in `swipe-content.js`.
- Class Inheritance: The Carousel class now extends SwipeContent.
- Attribute Handling: Attributes are accessed using this.element instead of directly.
- Drag Functionality: Introduced dragEnabled attribute to handle drag settings.
- Conditional Checks: Added checks for null values in styles and dimensions.
- Removal of Unused Methods: Removed alignControlsFunc method and related controls alignment logic.
- Example Updates: Adjusted our examples to demonstrate the drag functionality.

Thanks again for identifying this issue and providing a clear and effective solution.

We believe this fix should resolve the issue you've raised. Please review the update and let us know if you have any more problems.

**Closed** 2024-06-12 23:18 UTC
