### ISSUE TITLE
Focus ring for content block is not showing properly

### ISSUE THREAD

**Issue by cdbenj** [digitalnsw/nsw-design-system#145] opened 2021-05-03 01:07 UTC
The 'View More' link's focus ring's outlines are being covered
![Screen Shot 2021-05-03 at 11 04 52 am](https://user-images.githubusercontent.com/72421923/116833998-861d2800-abff-11eb-9c6e-fb80e4448b55.png)

**Comment by anna-yeshtukova** [comment] 2021-11-30 02:37
I had tested it and cannot reproduce it. Closing as it was likely fixed by all updates to 3.0.

**Closed by anna-yeshtukova** 2021-11-30 02:37 UTC
